[build-system]
requires = ["setuptools>=61.0", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "amisim"
dynamic = ["version"]
description = "Mesoscopic Traffic Assignment and Simulation Model"
readme = "README.md"
requires-python = ">=3.10"
authors = [ { name = "Andrea Gemma", email = "andrea.gemma@uniroma3.it" } ]
keywords = ["Mesoscopic", "Traffic", "Assignment", "Simulation"]

dependencies = []

[project.scripts]
amisim = "amisim.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
dev = [
  "pytest>=7.0",
  "flake8>=6.0",
  "mypy>=1.10",
  "build",
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203"]

[tool.mypy]
python_version = 3.10
strict = true
